### ISSUE TITLE
Delimiter for CsvFileSource not used

### ISSUE THREAD

**Issue by tokl** [pabloem/beam_utils#2]
Hi,

thanks a lot for writing this little library. It really helped me handling CSV Files. 

But since the delimiter in my files wasn't the default ",", I had problems getting the library to work.
It seems that in CsvFileSource you included an option for different CSV delimiters, but the options are actually never used.

`reader = csv.reader(self._file)`

should be:

`reader = csv.reader(self._file, delimiter=self.delimiter)`

Thanks for your help and best regards,
Tobias

**Comment by pabloem** [comment]
Hi Tobias. Ugh I'm sorry I missed that. I'll update it ASAP.

**Comment by pabloem** [comment]
Fixed in 701b8608. Also pushed new release with the fix.

**Comment by tokl** [comment]
Thanks for the incredibly fast fix!
